### PR TITLE
Added : how to create no pass SSH key

### PR DESCRIPTION
**Pull request by ankitsri11**
I have updated below ssh link :  
https://docs.snap-ci.com/getting-started/ssh-keys/

### CODE REVIEW

**Comment by ketan** [comment]
@ankitsri11 - there's a bunch of convention you have to know before submitting PRs.

Code is written in a very specific style using blocks in triple tilde, see [this page](https://docs.snap-ci.com/the-ci-environment/languages/php/) for an example.

In addition -

* You checked in a bunch of images that are not used anywhere.
* The new sections that you added don't gel well with the existing content, would you like to consider throwing what was there earlier and go along with the flow you have come up with. I'd like to make some improvements to your new flow -

# Check if you already have ssh keys

``` ls -al``` 

Skip to next section (with a link to the section) if you already have keys.

# Generate ssh keys

```ssh-keygen ...```

Drop the words about "we strongly suggest", that suggestion is not a very secure thing to do otherwise, but works well on CI systems.

# Add ssh key to snap

# Test your ssh key from snap

**Comment by ketan** [comment]
Needless to say, if you need any help with markdown; feel free to ping someone on the team.

**Comment by ankitsri11** [comment]
Have updated the content as per Ketan's feedback.

**Comment by ketan** [comment]
@ankitsri11 - Marking this as closed. Please see the edit here - https://github.com/snap-ci/docs.snap-ci.com/commit/6fe823501e140cf52a0c1246a6dfff0c56f0bebf

**Pull request closed without merging**
