### PR TITLE
Add info about knapsack gem

### PR DESCRIPTION
**Pull request by ArturT**
@ketan I added support for snap-ci in knapsack gem hence this pull request. Other tools like travis/semaphoreapp already have info about knapsack in their docs. Hope this will be helpful. :)

### CODE REVIEW

**Comment by akshaykarle** [comment]
@ArturT thanks a lot for the PR :)

**Comment by ArturT** [comment]
Please let me know when it will be visible here https://docs.snap-ci.com/speeding-up-builds/test-parallelism/ so I will add the link in knapsack gem read me.

**Comment by akshaykarle** [comment]
@ArturT I've made some changes and pushed out the documentation. You can add the following link to the knapsack readme https://docs.snap-ci.com/speeding-up-builds/test-parallelism/#parallelism-using-third-party-tools%23knapsack-optimal-test-suite-split-based-on-time-execution

**Comment by ArturT** [comment]
@akshaykarle Thanks! I placed link https://github.com/ArturT/knapsack#mentions

**Pull request merged**
