### PR TITLE
Add BuildCheckerApp in docs

### PR DESCRIPTION
**Pull request by willmendesneto**
- Add [BuildCheckerApp](https://github.com/willmendesneto/build-checker-app#readme) in docs page;
- Removes `CCMenu` reference in `doc_title`;

### CODE REVIEW

**Comment by willmendesneto** [comment]
@henriquerrezende @andreitognolo Can you take a look in this error, please?

screen shot 2016-04-27 at 10 07 08 pm

**Comment by willmendesneto** [comment]
Thanks @ibnc, but the build still failling. Can you update the Ruby version in Snap-CI build pipeline and try again, please? Ping @henriquerrezende @andreitognolo @fernando-alves @akshaykarle

**Comment by ibnc** [comment]
@willmendesneto It looks like it's passing to me.

https://snap-ci.com/snap-ci/docs.snap-ci.com/pull/10

**Comment by willmendesneto** [comment]
Was because I took a look in the repository badge and was with failling status, but now it's ok. Thanks for the feedback @ibnc

**Pull request merged**
